"""empty message

Revision ID: 833878fa5fc1
Revises: 99b1ae83f847
Create Date: 2021-10-16 18:22:23.350229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833878fa5fc1'
down_revision = '99b1ae83f847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genresList', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genresList')
    # ### end Alembic commands ###
