"""empty message

Revision ID: a8c3bc6d8601
Revises: 833878fa5fc1
Create Date: 2021-10-16 18:28:51.223949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8c3bc6d8601'
down_revision = '833878fa5fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'genresList')
    op.add_column('venue', sa.Column('genresl', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genresl')
    op.add_column('artist', sa.Column('genresList', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
